// SPDX-License-Identifier: MIT
// Copyright (c) 2026 @poyea

// Turning rendered greyscale bytes into files.

import { toImageData } from './pipeline.js';

let scratch = null;
let scratchImage = null;

/** Reusable canvas holding the rendered plate as RGBA. */
export function bytesToCanvas(bytes, width, height) {
  if (!scratch) scratch = document.createElement('canvas');
  if (scratch.width !== width || scratch.height !== height) {
    scratch.width = width;
    scratch.height = height;
    scratchImage = null;
  }
  scratchImage = toImageData(bytes, width, height, scratchImage);
  scratch.getContext('2d', { alpha: false }).putImageData(scratchImage, 0, 0);
  return scratch;
}

function toBlob(canvas, type, quality) {
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => (blob ? resolve(blob) : reject(new Error(`could not encode ${type}`))),
      type,
      quality,
    );
  });
}

export function encodeJpeg(bytes, width, height, quality = 0.92) {
  return toBlob(bytesToCanvas(bytes, width, height), 'image/jpeg', quality);
}

export function encodePng(bytes, width, height) {
  return toBlob(bytesToCanvas(bytes, width, height), 'image/png');
}

/**
 * Pack to 1 bit per pixel, MSB first, rows padded to whole bytes: the layout
 * every Waveshare-style driver expects.
 *
 * @param {Uint8ClampedArray} bytes
 * @param {'white1'|'black1'} polarity which colour a set bit means
 */
export function packMono(bytes, width, height, polarity = 'white1') {
  const rowBytes = Math.ceil(width / 8);
  const out = new Uint8Array(rowBytes * height);
  const setOnWhite = polarity === 'white1';
  for (let y = 0; y < height; y++) {
    const rowIn = y * width;
    const rowOut = y * rowBytes;
    for (let x = 0; x < width; x++) {
      const white = bytes[rowIn + x] >= 128;
      if (white === setOnWhite) out[rowOut + (x >> 3)] |= 0x80 >> (x & 7);
    }
  }
  return out;
}

export function encodeBin(bytes, width, height, polarity) {
  return new Blob([packMono(bytes, width, height, polarity)], { type: 'application/octet-stream' });
}

/** C header with the packed buffer as a byte array. */
export function encodeHeader(bytes, width, height, { polarity = 'white1', symbol } = {}) {
  const packed = packMono(bytes, width, height, polarity);
  const name = cIdentifier(symbol || `image_${width}x${height}`);
  const guard = `${name.toUpperCase()}_H`;
  const perLine = 16;

  const lines = [
    '/* Generated by inkmagine: https://github.com/poyea/inkmagine. */',
    `/* ${width} x ${height}, 1 bpp, MSB first, row-major.`,
    ` * A set bit is ${polarity === 'white1' ? 'white' : 'black'}.`,
    ` * ${packed.length} bytes (${Math.ceil(width / 8)} bytes per row).`,
    ' */',
    `#ifndef ${guard}`,
    `#define ${guard}`,
    '',
    '#include <stdint.h>',
    '',
    `#define ${name.toUpperCase()}_WIDTH  ${width}`,
    `#define ${name.toUpperCase()}_HEIGHT ${height}`,
    '',
    '/* Add PROGMEM here for AVR targets. */',
    `const uint8_t ${name}[${packed.length}] = {`,
  ];

  for (let i = 0; i < packed.length; i += perLine) {
    const chunk = [];
    for (let j = i; j < Math.min(i + perLine, packed.length); j++) {
      chunk.push(`0x${packed[j].toString(16).padStart(2, '0').toUpperCase()}`);
    }
    lines.push(`  ${chunk.join(', ')}${i + perLine < packed.length ? ',' : ''}`);
  }

  lines.push('};', '', `#endif /* ${guard} */`, '');
  return new Blob([lines.join('\n')], { type: 'text/plain' });
}

function cIdentifier(value) {
  const cleaned = value.replace(/[^A-Za-z0-9_]/g, '_').replace(/^(\d)/, '_$1');
  return cleaned || 'image';
}

export const FORMATS = {
  jpg: { ext: 'jpg', label: 'JPEG', encode: (b, w, h, o) => encodeJpeg(b, w, h, o.quality) },
  png: { ext: 'png', label: 'PNG', encode: (b, w, h) => encodePng(b, w, h) },
  bin: { ext: 'bin', label: '1bpp binary', encode: async (b, w, h, o) => encodeBin(b, w, h, o.polarity) },
  h: { ext: 'h', label: 'C header', encode: async (b, w, h, o) => encodeHeader(b, w, h, o) },
};

/** `beach.jpg` -> `beach-480x800.jpg` */
export function outputName(sourceName, width, height, ext) {
  const base = String(sourceName || 'image').replace(/\.[^.]+$/, '').replace(/[\\/:*?"<>|]+/g, '-');
  return `${base || 'image'}-${width}x${height}.${ext}`;
}

export function formatBytes(n) {
  if (!Number.isFinite(n)) return '—';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} kB`;
  return `${(n / (1024 * 1024)).toFixed(2)} MB`;
}
